const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{Fixar: 0},
	{Animacoes: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{jogador: 0},
	{Teclado: 0},
	{Joia: 0},
	{Âncora: 0},
	{Pontuação: 0},
	{Ação: 0},
	{Inimigo1: 0},
	{Parede1: 0},
	{Sprite2: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite3: 0},
	{Botão: 0},
	{Mouse: 0},
	{BotãoInicio: 0},
	{Sprite4: 0},
	{GAMEOVER: 0},
	{Texto: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{Sprite9: 0},
	{AnimaçãoF2: 0},
	{JOGADORF2: 0},
	{Joia2: 0},
	{PONTUAÇÃO2: 0},
	{Inimigo2: 0},
	{Parede2: 0},
	{PlanoDeFundoEmBlocos8: 0},
	{Espinho10: 0},
	{Sprite10: 0},
	{PlanoDeFundoEmBlocos9: 0},
	{PlanoDeFundoEmBlocos10: 0},
	{luz: 0},
	{luz2: 0},
	{fogo: 0},
	{PlanoDeFundoEmBlocos11: 0},
	{luz3: 0},
	{PlanoDeFundoEmBlocos12: 0},
	{Sprite: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	Animacoes: class extends self.ISpriteInstance {},
	jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Joia: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	Inimigo1: class extends self.ISpriteInstance {},
	Parede1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Botão: class extends self.IButtonInstance {},
	Mouse: class extends self.IInstance {},
	BotãoInicio: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	GAMEOVER: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	AnimaçãoF2: class extends self.ISpriteInstance {},
	JOGADORF2: class extends self.ISpriteInstance {},
	Joia2: class extends self.ISpriteInstance {},
	PONTUAÇÃO2: class extends self.ITextInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	Parede2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	Espinho10: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos9: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos10: class extends self.ITiledBackgroundInstance {},
	luz: class extends self.ISpriteInstance {},
	luz2: class extends self.ISpriteInstance {},
	fogo: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos11: class extends self.ITiledBackgroundInstance {},
	luz3: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos12: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {}
}